language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
  - clang
env:
  - ROS_DISTRO=hydro
matrix:
  allow_failures:
    - compiler: clang
notifications:
  - email: false

before_install:
  - CI_SOURCE_PATH=$(pwd)
  - REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"

install:
  - source <(wget -O- https://raw.githubusercontent.com/tue-robotics/tue-env/master/installer/scripts/bootstrap-ros-$ROS_DISTRO)
  - tue-get install ros-${REPOSITORY_NAME}
  - source ~/.tue/setup.bash # source all target setup files

before_script:
  - cd ${TUE_SYSTEM_DIR}/src

  # Link the repo we are testing to the new workspace
  - rm -rf $REPOSITORY_NAME
  - ln -s $CI_SOURCE_PATH .
  - ls -l
  - cd .. # go to the catkin workspace

script:
  - catkin_make -j2
  - catkin_make install   # installing the package
  - catkin_make tests     # build the tests
  - catkin_make run_tests # and run them
